# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# enable for debugging

# debugpy:

# Text to speech
tts:
  - platform: google_translate

logger:
  default: warning
  logs:
    custom_components.moonraker: warning
