#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

sudo apt-get update
sudo apt-get install -y libturbojpeg0 ffmpeg


python3 -m pip install --requirement requirements.txt

# https://github.com/home-assistant/core/issues/95192
pip install git+https://github.com/boto/botocore

pre-commit install
