send_gcode:
  name: "Send G-code"
  description: "Send a custom G-code command to the printer"
  fields:
    device_id:
      name: "Printer"
      description: "Moonraker device that should receive the G-code"
      required: true
      selector:
        device:
          integration: moonraker
    gcode:
      name: "G-code"
      description: "G-code command to send to the printer"
      required: true
      example: "G28"
      selector:
        text:
